spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: 'lb://auth-service'
          predicates:
            - Path=/auth/**
        - id: account-service
          uri: 'lb://account-service'
          predicates:
            - Path=/account/**
      default-filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10 # 允许用户每秒处理多少个请求  (令牌桶每秒填充平均速率)
            redis-rate-limiter.burstCapacity: 20 # 允许在一秒钟内完成的最大请求数 (令牌桶总容量)
            key-resolver: "#{@ipKeyResolver}" # 限流策略，对应策略的Bean
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback