spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.39.29:3366/sc_test
    username: root
    password: admin
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 100